### ISSUE TITLE
Add dependencies to setup.py file

### ISSUE THREAD

**Issue by jvfe** [lubianat/wdcuration#7]
Currently no requirements are set in setup.py

**Comment by jvfe** [comment]
Hey @lubianat even though this is fixed, it isn't up on PyPI yet, so you still need to bump the version and upload it

**Comment by lubianat** [comment]
Sure, thanks. I've been bumping versions manually, do you have a workflow
for that?

Em ter., 24 de jan. de 2023 10:19, João Vitor ***@***.***>
escreveu:
